<?xml version="1.0" encoding="utf-8"?>
<!--
  PROJECT:    NanaGet
  FILE:       NanaGet.Project.props
  PURPOSE:    MSBuild Properties for NanaGet Common Properties

  LICENSE:    The MIT License

  MAINTAINER: MouriNaruto (Kenji.Mouri@outlook.com)
-->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildThisFileDirectory)NanaGet.Project.Version.props" />
  <PropertyGroup>
    <NanaGetBuildNumberDate Condition="'$(NanaGetBuildNumberDate)' == ''">$([System.DateTime]::Today.ToString('yyyy-MM-dd'))</NanaGetBuildNumberDate>
    <NanaGetProjectCreationDate>2022-04-25</NanaGetProjectCreationDate>
    <MileProjectVersion>$(NanaGetMajorVersion).$(NanaGetMinorVersion).$([System.DateTime]::Parse('$(NanaGetBuildNumberDate)').Subtract($([System.DateTime]::Parse('$(NanaGetProjectCreationDate)'))).TotalDays).0</MileProjectVersion>
    <MileProjectVersionTag>$(NanaGetVersionTag)</MileProjectVersionTag>
    <NanaGetBuildPreviewRelease Condition="'$(NanaGetBuildPreviewRelease)' == '' And $([System.String]::Copy('$(NanaGetVersionTag)').Contains('Preview'))">true</NanaGetBuildPreviewRelease>
    <NanaGetBuildPreviewRelease Condition="'$(NanaGetBuildPreviewRelease)' == '' And $([System.String]::Copy('$(NanaGetVersionTag)').Contains('Final'))">true</NanaGetBuildPreviewRelease>
    <NanaGetBuildPreviewRelease Condition="'$(NanaGetBuildPreviewRelease)' == ''">false</NanaGetBuildPreviewRelease>
  </PropertyGroup>
</Project>